In [1]:
import scipy as sp

In [2]:
#scipy.linalg, scipy.special, scipy.integrate, scipy.optimize, scipy.fftpack, scipy.signal, 
#scipy.stats, scipy.ndimage, scipy.io

In [3]:
import numpy as np
from scipy import linalg

In [4]:
A = np.array([[1,2], [3,4]])
print(A)
B = linalg.inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
A = np.array([[1,3,5], [2,5,1], [2,3,8]])
print(A)
b = np.array([[10], [8], [3]])
print(b)
#fast
print("np.linalg.solve(A, b) ile denklem çözümü")
print(np.linalg.solve(A,b))
#slow
print("linalg.inv(A).dot(b) ile denklem çözümü")
print(linalg.inv(A).dot(b))

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]
np.linalg.solve(A, b) ile denklem çözümü
[[-9.28]
 [ 5.16]
 [ 0.76]]
linalg.inv(A).dot(b) ile denklem çözümü
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [7]:
from scipy import integrate
x2 = lambda x : x**2
I = integrate.quad(x2, 0, 6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [8]:
import scipy.integrate as integrate
import scipy.special as special
#bessel function
result = integrate.quad(lambda x : special.jv(2.5, x), 0, 4.5)
print(result)

(1.1178179380783244, 7.866317216380707e-09)


In [9]:
#Türev
from scipy.misc import derivative
def f(x):
    return x**3 + x**2
D = derivative(f, 1.0, dx = 1e-6)
print(D)

4.999999999921734


In [10]:
#PANDAS

In [14]:
import pandas as pd

In [15]:
import warnings
warnings.filterwarnings('ignore')

In [16]:
#Seriler

In [17]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [18]:
s1.dtype

dtype('int32')

In [20]:
s1.values.itemsize

4

In [21]:
s1.nbytes

28

In [22]:
#shape, ndim, len(s1), count(), size

In [23]:
s0 = pd.Series([1,2,3], index = ['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [24]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [25]:
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.12856903, 0.53257235, 0.35374605, 0.60374297, 0.21252081,
        0.71802634, 0.84248329, 0.5681142 , 0.47076303, 0.29325531]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.128569
 1    0.532572
 2    0.353746
 3    0.603743
 4    0.212521
 5    0.718026
 6    0.842483
 7    0.568114
 8    0.470763
 9    0.293255
 dtype: float64)

In [26]:
dict1 = {'a1' : 10, 'a2' : 20, 'a3' : 30, 'a4' : 40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [27]:
pd.Series(99, index = [0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [28]:
s

0    0.128569
1    0.532572
2    0.353746
3    0.603743
4    0.212521
5    0.718026
6    0.842483
7    0.568114
8    0.470763
9    0.293255
dtype: float64

In [29]:
s[0:3]

0    0.128569
1    0.532572
2    0.353746
dtype: float64

In [30]:
s[-1:]

9    0.293255
dtype: float64

In [31]:
s[:4]

0    0.128569
1    0.532572
2    0.353746
3    0.603743
dtype: float64

In [32]:
s[-3:-1]

7    0.568114
8    0.470763
dtype: float64

In [33]:
#Serileri Birleştirme (Append)

In [34]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [35]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [36]:
s4 = s2.append(s3)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [37]:
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [38]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [39]:
s4.drop('a4', inplace = True)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [40]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [41]:
s4 = s4.append(pd.Series({'a4' : 7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [42]:
#Seriler üzerindeki işlemler

In [43]:
v1 = np.array([10,20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1, s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [44]:
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [45]:
s1.sub(s2)

0     9
1    18
2    27
dtype: int32

In [46]:
s1.subtract(s2)

0     9
1    18
2    27
dtype: int32

In [47]:
s1.add(9)

0    19
1    29
2    39
dtype: int32

In [48]:
s1.mul(s2)

0    10
1    40
2    90
dtype: int32

In [49]:
s1.multiply(s2)

0    10
1    40
2    90
dtype: int32

In [50]:
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int32

In [51]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [52]:
s1.div(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [53]:
#max(), min(), mean(), median(), std()

In [54]:
s5 = pd.Series([1,1,2,2,3,3], index = [0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [55]:
s5.value_counts()

1    2
2    2
3    2
dtype: int64

In [56]:
#DATAFRAMES (Veri Çerçeveleri)

In [57]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [58]:
lang = ['Java', 'Python', 'C', 'C++']
df = pd.DataFrame(lang)
df

0
0    Java
1  Python
2       C
3     C++

In [59]:
rating = [1,2,3,4]
df[1] = rating
df

0  1
0    Java  1
1  Python  2
2       C  3
3     C++  4

In [60]:
df.columns = ['Language', 'Rating']

In [61]:
df

Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [62]:
data = [{'a' : 1, 'b' : 2}, {'a' : 5, 'b' : 10, 'c' : 20}]

df2 = pd.DataFrame(data)
df3 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b'])
df4 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c'])
df5 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c', 'd'])

In [63]:
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [64]:
df3

a   b
row1  1   2
row2  5  10

In [65]:
df4

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [66]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [67]:
mydict = {'A' : pd.Series([1,2,3], index = ['a', 'b', 'c']),
          'B' : pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}

df1 = pd.DataFrame(mydict)
df1

A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

In [68]:
#Data indeksi ve random sayılar kullanarak DF oluşturma

In [69]:
dates = pd.date_range(start = '2023-12-01', end = '2023-12-07')
dates

DatetimeIndex(['2023-12-01', '2023-12-02', '2023-12-03', '2023-12-04',
               '2023-12-05', '2023-12-06', '2023-12-07'],
              dtype='datetime64[ns]', freq='D')

In [70]:
dates = pd.date_range('today', periods = 7)
dates

DatetimeIndex(['2023-12-04 21:40:09.067735', '2023-12-05 21:40:09.067735',
               '2023-12-06 21:40:09.067735', '2023-12-07 21:40:09.067735',
               '2023-12-08 21:40:09.067735', '2023-12-09 21:40:09.067735',
               '2023-12-10 21:40:09.067735'],
              dtype='datetime64[ns]', freq='D')

In [71]:
dates = pd.date_range(start = '2023-12-01', periods = 7)
dates

DatetimeIndex(['2023-12-01', '2023-12-02', '2023-12-03', '2023-12-04',
               '2023-12-05', '2023-12-06', '2023-12-07'],
              dtype='datetime64[ns]', freq='D')

In [72]:
M = np.random.random((7,7))
M

array([[0.29257341, 0.881794  , 0.55159866, 0.64624192, 0.84137201,
        0.5245319 , 0.63912318],
       [0.20097121, 0.22743925, 0.09067676, 0.97971716, 0.86430182,
        0.20749689, 0.95043004],
       [0.94103378, 0.84651798, 0.90173809, 0.50888181, 0.84858153,
        0.82695521, 0.97098941],
       [0.05752817, 0.71947771, 0.79833377, 0.59246469, 0.41983534,
        0.83638781, 0.94352356],
       [0.40625977, 0.57648065, 0.69156724, 0.10407004, 0.51693518,
        0.19511422, 0.41623244],
       [0.07365965, 0.25981928, 0.8565292 , 0.54818433, 0.71232895,
        0.61152174, 0.73789689],
       [0.66363395, 0.75845459, 0.88617459, 0.29434497, 0.05048049,
        0.93716848, 0.97276838]])

In [73]:
dframe = pd.DataFrame(M, index = dates)
dframe

0         1         2         3         4         5  \
2023-12-01  0.292573  0.881794  0.551599  0.646242  0.841372  0.524532   
2023-12-02  0.200971  0.227439  0.090677  0.979717  0.864302  0.207497   
2023-12-03  0.941034  0.846518  0.901738  0.508882  0.848582  0.826955   
2023-12-04  0.057528  0.719478  0.798334  0.592465  0.419835  0.836388   
2023-12-05  0.406260  0.576481  0.691567  0.104070  0.516935  0.195114   
2023-12-06  0.073660  0.259819  0.856529  0.548184  0.712329  0.611522   
2023-12-07  0.663634  0.758455  0.886175  0.294345  0.050480  0.937168   

                   6  
2023-12-01  0.639123  
2023-12-02  0.950430  
2023-12-03  0.970989  
2023-12-04  0.943524  
2023-12-05  0.416232  
2023-12-06  0.737897  
2023-12-07  0.972768

In [74]:
dframe.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

C1        C2        C3        C4        C5        C6  \
2023-12-01  0.292573  0.881794  0.551599  0.646242  0.841372  0.524532   
2023-12-02  0.200971  0.227439  0.090677  0.979717  0.864302  0.207497   
2023-12-03  0.941034  0.846518  0.901738  0.508882  0.848582  0.826955   
2023-12-04  0.057528  0.719478  0.798334  0.592465  0.419835  0.836388   
2023-12-05  0.406260  0.576481  0.691567  0.104070  0.516935  0.195114   
2023-12-06  0.073660  0.259819  0.856529  0.548184  0.712329  0.611522   
2023-12-07  0.663634  0.758455  0.886175  0.294345  0.050480  0.937168   

                  C7  
2023-12-01  0.639123  
2023-12-02  0.950430  
2023-12-03  0.970989  
2023-12-04  0.943524  
2023-12-05  0.416232  
2023-12-06  0.737897  
2023-12-07  0.972768

In [75]:
dframe.dtypes

C1    float64
C2    float64
C3    float64
C4    float64
C5    float64
C6    float64
C7    float64
dtype: object

In [76]:
dframe.sort_values(by = 'C1') #ascending

C1        C2        C3        C4        C5        C6  \
2023-12-04  0.057528  0.719478  0.798334  0.592465  0.419835  0.836388   
2023-12-06  0.073660  0.259819  0.856529  0.548184  0.712329  0.611522   
2023-12-02  0.200971  0.227439  0.090677  0.979717  0.864302  0.207497   
2023-12-01  0.292573  0.881794  0.551599  0.646242  0.841372  0.524532   
2023-12-05  0.406260  0.576481  0.691567  0.104070  0.516935  0.195114   
2023-12-07  0.663634  0.758455  0.886175  0.294345  0.050480  0.937168   
2023-12-03  0.941034  0.846518  0.901738  0.508882  0.848582  0.826955   

                  C7  
2023-12-04  0.943524  
2023-12-06  0.737897  
2023-12-02  0.950430  
2023-12-01  0.639123  
2023-12-05  0.416232  
2023-12-07  0.972768  
2023-12-03  0.970989

In [77]:
dframe.sort_values(by = 'C1', ascending = False) #descending 

C1        C2        C3        C4        C5        C6  \
2023-12-03  0.941034  0.846518  0.901738  0.508882  0.848582  0.826955   
2023-12-07  0.663634  0.758455  0.886175  0.294345  0.050480  0.937168   
2023-12-05  0.406260  0.576481  0.691567  0.104070  0.516935  0.195114   
2023-12-01  0.292573  0.881794  0.551599  0.646242  0.841372  0.524532   
2023-12-02  0.200971  0.227439  0.090677  0.979717  0.864302  0.207497   
2023-12-06  0.073660  0.259819  0.856529  0.548184  0.712329  0.611522   
2023-12-04  0.057528  0.719478  0.798334  0.592465  0.419835  0.836388   

                  C7  
2023-12-03  0.970989  
2023-12-07  0.972768  
2023-12-05  0.416232  
2023-12-01  0.639123  
2023-12-02  0.950430  
2023-12-06  0.737897  
2023-12-04  0.943524

In [78]:
#Sütun Silme

In [79]:
df1

A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

In [80]:
del df1['B']

In [81]:
df1

A
a  1.0
b  2.0
c  3.0
d  NaN

In [82]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [83]:
#push, pop

In [84]:
df5.pop('c')

row1     NaN
row2    20.0
Name: c, dtype: float64

In [85]:
df5

a   b   d
row1  1   2 NaN
row2  5  10 NaN

In [87]:
mydict = {'A' : pd.Series([1,2,3,11], index = ['a', 'b', 'c', 'd']),
          'B' : pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}

df12 = pd.DataFrame(mydict)
df12

A  B
a   1  1
b   2  2
c   3  3
d  11  4

In [88]:
df12.drop(['A'], axis = 1, inplace = True)
df12

B
a  1
b  2
c  3
d  4

In [89]:
#Satır Silme

In [90]:
col1 = np.linspace(10, 100, 30)
col2 = np.random.randint(10, 100, 30)
df10 = pd.DataFrame({"C1" : col1, "C2" : col2})
df10

C1  C2
0    10.000000  78
1    13.103448  67
2    16.206897  80
3    19.310345  84
4    22.413793  90
5    25.517241  48
6    28.620690  22
7    31.724138  51
8    34.827586  29
9    37.931034  68
10   41.034483  20
11   44.137931  91
12   47.241379  84
13   50.344828  16
14   53.448276  14
15   56.551724  42
16   59.655172  25
17   62.758621  59
18   65.862069  90
19   68.965517  58
20   72.068966  40
21   75.172414  44
22   78.275862  83
23   81.379310  33
24   84.482759  10
25   87.586207  34
26   90.689655  84
27   93.793103  40
28   96.896552  61
29  100.000000  91

In [91]:
df10 = df10.drop([17, 18, 19], axis = 0)
df10

C1  C2
0    10.000000  78
1    13.103448  67
2    16.206897  80
3    19.310345  84
4    22.413793  90
5    25.517241  48
6    28.620690  22
7    31.724138  51
8    34.827586  29
9    37.931034  68
10   41.034483  20
11   44.137931  91
12   47.241379  84
13   50.344828  16
14   53.448276  14
15   56.551724  42
16   59.655172  25
20   72.068966  40
21   75.172414  44
22   78.275862  83
23   81.379310  33
24   84.482759  10
25   87.586207  34
26   90.689655  84
27   93.793103  40
28   96.896552  61
29  100.000000  91

In [92]:
df10.drop([16], axis = 0, inplace = True)
df10

C1  C2
0    10.000000  78
1    13.103448  67
2    16.206897  80
3    19.310345  84
4    22.413793  90
5    25.517241  48
6    28.620690  22
7    31.724138  51
8    34.827586  29
9    37.931034  68
10   41.034483  20
11   44.137931  91
12   47.241379  84
13   50.344828  16
14   53.448276  14
15   56.551724  42
20   72.068966  40
21   75.172414  44
22   78.275862  83
23   81.379310  33
24   84.482759  10
25   87.586207  34
26   90.689655  84
27   93.793103  40
28   96.896552  61
29  100.000000  91

In [93]:
df10.drop(df10.index[5], inplace = True)
df10

C1  C2
0    10.000000  78
1    13.103448  67
2    16.206897  80
3    19.310345  84
4    22.413793  90
6    28.620690  22
7    31.724138  51
8    34.827586  29
9    37.931034  68
10   41.034483  20
11   44.137931  91
12   47.241379  84
13   50.344828  16
14   53.448276  14
15   56.551724  42
20   72.068966  40
21   75.172414  44
22   78.275862  83
23   81.379310  33
24   84.482759  10
25   87.586207  34
26   90.689655  84
27   93.793103  40
28   96.896552  61
29  100.000000  91

In [94]:
df10 = df10.iloc[3:,]
df10

C1  C2
3    19.310345  84
4    22.413793  90
6    28.620690  22
7    31.724138  51
8    34.827586  29
9    37.931034  68
10   41.034483  20
11   44.137931  91
12   47.241379  84
13   50.344828  16
14   53.448276  14
15   56.551724  42
20   72.068966  40
21   75.172414  44
22   78.275862  83
23   81.379310  33
24   84.482759  10
25   87.586207  34
26   90.689655  84
27   93.793103  40
28   96.896552  61
29  100.000000  91

In [95]:
df10 = df10.iloc[:-3,]
df10

C1  C2
3   19.310345  84
4   22.413793  90
6   28.620690  22
7   31.724138  51
8   34.827586  29
9   37.931034  68
10  41.034483  20
11  44.137931  91
12  47.241379  84
13  50.344828  16
14  53.448276  14
15  56.551724  42
20  72.068966  40
21  75.172414  44
22  78.275862  83
23  81.379310  33
24  84.482759  10
25  87.586207  34
26  90.689655  84

In [96]:
df10.index[df10['C2'] == 84].tolist()

[3, 12, 26]

In [97]:
df13 = pd.DataFrame({'ID' : [1,2,3,4],
                    'Name' : ['Doğu', 'Batı', 'Kuzey', 'Güney'],
                    'location' : ['India', 'Australia', 'UK', 'US']})
df13

ID   Name   location
0   1   Doğu      India
1   2   Batı  Australia
2   3  Kuzey         UK
3   4  Güney         US

In [98]:
ind = df13[((df13.Name == 'Kuzey') & (df13.ID == 3) & (df13.location == 'UK'))].index
df13.drop(ind, inplace = True)
df13

ID   Name   location
0   1   Doğu      India
1   2   Batı  Australia
3   4  Güney         US

In [99]:
dframe

C1        C2        C3        C4        C5        C6  \
2023-12-01  0.292573  0.881794  0.551599  0.646242  0.841372  0.524532   
2023-12-02  0.200971  0.227439  0.090677  0.979717  0.864302  0.207497   
2023-12-03  0.941034  0.846518  0.901738  0.508882  0.848582  0.826955   
2023-12-04  0.057528  0.719478  0.798334  0.592465  0.419835  0.836388   
2023-12-05  0.406260  0.576481  0.691567  0.104070  0.516935  0.195114   
2023-12-06  0.073660  0.259819  0.856529  0.548184  0.712329  0.611522   
2023-12-07  0.663634  0.758455  0.886175  0.294345  0.050480  0.937168   

                  C7  
2023-12-01  0.639123  
2023-12-02  0.950430  
2023-12-03  0.970989  
2023-12-04  0.943524  
2023-12-05  0.416232  
2023-12-06  0.737897  
2023-12-07  0.972768

In [100]:
dframe['2023-12-01' : '2023-12-03']

C1        C2        C3        C4        C5        C6  \
2023-12-01  0.292573  0.881794  0.551599  0.646242  0.841372  0.524532   
2023-12-02  0.200971  0.227439  0.090677  0.979717  0.864302  0.207497   
2023-12-03  0.941034  0.846518  0.901738  0.508882  0.848582  0.826955   

                  C7  
2023-12-01  0.639123  
2023-12-02  0.950430  
2023-12-03  0.970989

In [101]:
dframe.loc[:, ['C1', 'C7']]

C1        C7
2023-12-01  0.292573  0.639123
2023-12-02  0.200971  0.950430
2023-12-03  0.941034  0.970989
2023-12-04  0.057528  0.943524
2023-12-05  0.406260  0.416232
2023-12-06  0.073660  0.737897
2023-12-07  0.663634  0.972768

In [102]:
dframe.loc['2023-12-01' : '2023-12-03', ['C1', 'C7']]

C1        C7
2023-12-01  0.292573  0.639123
2023-12-02  0.200971  0.950430
2023-12-03  0.941034  0.970989

In [103]:
dframe[dframe['C1'] > 0.5]

C1        C2        C3        C4        C5        C6  \
2023-12-03  0.941034  0.846518  0.901738  0.508882  0.848582  0.826955   
2023-12-07  0.663634  0.758455  0.886175  0.294345  0.050480  0.937168   

                  C7  
2023-12-03  0.970989  
2023-12-07  0.972768

In [104]:
dframe[(dframe['C1'] > 0.5) & (dframe['C4'] > 0.5)]

C1        C2        C3        C4        C5        C6  \
2023-12-03  0.941034  0.846518  0.901738  0.508882  0.848582  0.826955   

                  C7  
2023-12-03  0.970989

In [105]:
dframe.iloc[0][0]

0.2925734052893988

In [106]:
#Değer Atama

In [107]:
dframe['C1'] = 888
dframe

C1        C2        C3        C4        C5        C6        C7
2023-12-01  888  0.881794  0.551599  0.646242  0.841372  0.524532  0.639123
2023-12-02  888  0.227439  0.090677  0.979717  0.864302  0.207497  0.950430
2023-12-03  888  0.846518  0.901738  0.508882  0.848582  0.826955  0.970989
2023-12-04  888  0.719478  0.798334  0.592465  0.419835  0.836388  0.943524
2023-12-05  888  0.576481  0.691567  0.104070  0.516935  0.195114  0.416232
2023-12-06  888  0.259819  0.856529  0.548184  0.712329  0.611522  0.737897
2023-12-07  888  0.758455  0.886175  0.294345  0.050480  0.937168  0.972768

In [108]:
dframe.loc[0:3, 'C6'] = 777

In [109]:
dframe

C1        C2        C3        C4        C5          C6        C7
2023-12-01  888  0.881794  0.551599  0.646242  0.841372  777.000000  0.639123
2023-12-02  888  0.227439  0.090677  0.979717  0.864302  777.000000  0.950430
2023-12-03  888  0.846518  0.901738  0.508882  0.848582  777.000000  0.970989
2023-12-04  888  0.719478  0.798334  0.592465  0.419835    0.836388  0.943524
2023-12-05  888  0.576481  0.691567  0.104070  0.516935    0.195114  0.416232
2023-12-06  888  0.259819  0.856529  0.548184  0.712329    0.611522  0.737897
2023-12-07  888  0.758455  0.886175  0.294345  0.050480    0.937168  0.972768

In [110]:
dframe.iloc[0, 2] = 333

In [111]:
dframe

C1        C2          C3        C4        C5          C6  \
2023-12-01  888  0.881794  333.000000  0.646242  0.841372  777.000000   
2023-12-02  888  0.227439    0.090677  0.979717  0.864302  777.000000   
2023-12-03  888  0.846518    0.901738  0.508882  0.848582  777.000000   
2023-12-04  888  0.719478    0.798334  0.592465  0.419835    0.836388   
2023-12-05  888  0.576481    0.691567  0.104070  0.516935    0.195114   
2023-12-06  888  0.259819    0.856529  0.548184  0.712329    0.611522   
2023-12-07  888  0.758455    0.886175  0.294345  0.050480    0.937168   

                  C7  
2023-12-01  0.639123  
2023-12-02  0.950430  
2023-12-03  0.970989  
2023-12-04  0.943524  
2023-12-05  0.416232  
2023-12-06  0.737897  
2023-12-07  0.972768

In [112]:
dframe.iloc[0, 2] = 555

In [113]:
dframe

C1        C2          C3        C4        C5          C6  \
2023-12-01  888  0.881794  555.000000  0.646242  0.841372  777.000000   
2023-12-02  888  0.227439    0.090677  0.979717  0.864302  777.000000   
2023-12-03  888  0.846518    0.901738  0.508882  0.848582  777.000000   
2023-12-04  888  0.719478    0.798334  0.592465  0.419835    0.836388   
2023-12-05  888  0.576481    0.691567  0.104070  0.516935    0.195114   
2023-12-06  888  0.259819    0.856529  0.548184  0.712329    0.611522   
2023-12-07  888  0.758455    0.886175  0.294345  0.050480    0.937168   

                  C7  
2023-12-01  0.639123  
2023-12-02  0.950430  
2023-12-03  0.970989  
2023-12-04  0.943524  
2023-12-05  0.416232  
2023-12-06  0.737897  
2023-12-07  0.972768

In [114]:
#Null değerlerle ilgilenme

In [115]:
dframe.loc[0:8, 'C7'] = np.NaN
dframe.loc[0:2, 'C6'] = np.NaN
dframe.loc[5:6, 'C5'] = np.NaN
dframe

C1        C2          C3        C4        C5          C6  C7
2023-12-01  888  0.881794  555.000000  0.646242  0.841372         NaN NaN
2023-12-02  888  0.227439    0.090677  0.979717  0.864302         NaN NaN
2023-12-03  888  0.846518    0.901738  0.508882  0.848582  777.000000 NaN
2023-12-04  888  0.719478    0.798334  0.592465  0.419835    0.836388 NaN
2023-12-05  888  0.576481    0.691567  0.104070  0.516935    0.195114 NaN
2023-12-06  888  0.259819    0.856529  0.548184       NaN    0.611522 NaN
2023-12-07  888  0.758455    0.886175  0.294345  0.050480    0.937168 NaN

In [116]:
dframe.isna()

C1     C2     C3     C4     C5     C6    C7
2023-12-01  False  False  False  False  False   True  True
2023-12-02  False  False  False  False  False   True  True
2023-12-03  False  False  False  False  False  False  True
2023-12-04  False  False  False  False  False  False  True
2023-12-05  False  False  False  False  False  False  True
2023-12-06  False  False  False  False   True  False  True
2023-12-07  False  False  False  False  False  False  True

In [117]:
dframe.notna()

C1    C2    C3    C4     C5     C6     C7
2023-12-01  True  True  True  True   True  False  False
2023-12-02  True  True  True  True   True  False  False
2023-12-03  True  True  True  True   True   True  False
2023-12-04  True  True  True  True   True   True  False
2023-12-05  True  True  True  True   True   True  False
2023-12-06  True  True  True  True  False   True  False
2023-12-07  True  True  True  True   True   True  False

In [118]:
dframe = dframe.fillna(1020)
dframe

C1        C2          C3        C4           C5           C6  \
2023-12-01  888  0.881794  555.000000  0.646242     0.841372  1020.000000   
2023-12-02  888  0.227439    0.090677  0.979717     0.864302  1020.000000   
2023-12-03  888  0.846518    0.901738  0.508882     0.848582   777.000000   
2023-12-04  888  0.719478    0.798334  0.592465     0.419835     0.836388   
2023-12-05  888  0.576481    0.691567  0.104070     0.516935     0.195114   
2023-12-06  888  0.259819    0.856529  0.548184  1020.000000     0.611522   
2023-12-07  888  0.758455    0.886175  0.294345     0.050480     0.937168   

                C7  
2023-12-01  1020.0  
2023-12-02  1020.0  
2023-12-03  1020.0  
2023-12-04  1020.0  
2023-12-05  1020.0  
2023-12-06  1020.0  
2023-12-07  1020.0