In [1]:
#Sözlükler (Dictionary)

In [2]:
mydict = {'Name' : 'Azra', 'Age' : 6, 'Class' : 'First'} #key-value pair
print("mydict['Name']:", mydict['Name'])
print("mydict['Age']:", mydict['Age'])

mydict['Name']: Azra
mydict['Age']: 6


In [3]:
#updating (güncelleme)
mydict['Age'] = 8
mydict['School'] = "Primary School"

In [4]:
print("mydict['Age']:", mydict['Age'])
print("mydict['School']:", mydict['School'])

mydict['Age']: 8
mydict['School']: Primary School


In [5]:
#mutable / immutable
b = "Primary School"
b[5] = 'c'
print(b)

TypeError: 'str' object does not support item assignment

In [6]:
#deleting (silme)
del mydict['Name']
mydict.clear()
del mydict

In [7]:
print("mydict['Age']:", mydict['Age'])
print("mydict['School']:", mydict['School'])

NameError: name 'mydict' is not defined

In [8]:
#get/items
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222'}
value = phonebook.get('Katie')
print(value)

555-2222


In [9]:
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222', 'Jason' : '555-3333'}
for key, value in phonebook.items():
    print(key, ':', value)

Chris : 555-1111
Katie : 555-2222
Jason : 555-3333


In [10]:
#NumPy

In [11]:
import numpy as np

In [12]:
import warnings
warnings.filterwarnings('ignore')

In [13]:
list1 = [10, 20, 30, 40, 50, 60]
list1

[10, 20, 30, 40, 50, 60]

In [14]:
type(list1)

list

In [15]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [16]:
arr1.data

In [17]:
type(arr1)

numpy.ndarray

In [19]:
arr1.dtype

dtype('int32')

In [20]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [21]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [27]:
a = np.array([10, 20, 30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [28]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [32]:
ar1 = np.arange(1, 20)
ar1[ar1 %2 == 1] 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
ar1 = np.arange(0, 22)
ar1[ar1 %2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [36]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [37]:
#Rastgele Sayılar

In [38]:
np.random.random(4)

array([0.34923098, 0.78218591, 0.91149813, 0.37512047])

In [39]:
np.random.randint(0, 500, 5)

array([262,  51, 433,  42,  14])

In [40]:
np.random.randint(0, 500, 10)

array([289, 347, 422,  30, 491, 410, 262, 179, 403,   0])

In [41]:
#seed (çekirdek)
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [42]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [43]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [44]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [45]:
np.random.randint(0, 100, 10)

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [46]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([5.90946201, 8.92800881, 9.82741611, 6.16176831, 5.41780717,
       8.01774211, 8.64496379, 6.38119414, 8.42653164, 7.58933737])

In [47]:
np.floor(f1)

array([5., 8., 9., 6., 5., 8., 8., 6., 8., 7.])

In [48]:
np.trunc(f1)

array([5., 8., 9., 6., 5., 8., 8., 6., 8., 7.])

In [49]:
f1.astype(int)

array([5, 8, 9, 6, 5, 8, 8, 6, 8, 7])

In [50]:
#Normal distribution
b2 = np.random.randn(10)
b2

array([ 2.60596728,  0.68350889,  0.30266545,  1.69372293, -1.70608593,
       -1.15911942, -0.13484072,  0.39052784,  0.16690464,  0.18450186])

In [51]:
arr1

array([10, 20, 30, 40, 50, 60])

In [52]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [53]:
#Dizi Üzerinde Yapılabilecek Operasyonlar

In [54]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [55]:
arr2.sum()

190

In [56]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [57]:
#min(), max(), argmin(), argmax(), mean(), median(), var()

In [58]:
np.std(arr2)

5.477225575051661

In [59]:
#2D Diziler Üzerindeki Operasyonlar

In [60]:
A = np.array([[1,2,3,0], [5,6,7,22], [10, 11, 1, 13], [14, 15, 16, 3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [61]:
A.sum()

129

In [62]:
#max(), min()

In [63]:
np.amin(A, axis = 0) #sütundaki minimumlar

array([1, 2, 1, 0])

In [64]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [65]:
#mean(), median(), var(), std()

In [66]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [67]:
#Eleman Yer Değiştirme

In [69]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [70]:
rep1 = np.where(ar %2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [71]:
ar2 = np.array([10, 20, 30, 10, 10, 20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [72]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [74]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [75]:
np.put(p2, [0, 3, 5], [33, 55, 99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [ ]:
#Missing Values (Eksik Değerler)